### ISSUE TITLE
tagfile not tagging a file created by vi

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/zos-code-page-toolsport#2]
Is this expected?

bash-5.2$ ls -lT TT
m IBM-1047    T=off -rw-rw-r--   1 @02858   @ISSTC00       6 Dec  7 18:31 TT

bash-5.2$ tagfile TT
file: TT file tag unchanged t:0 ccsid:1047
Done, 0 errors detected

bash-5.2$ ls -lT TT
m IBM-1047    T=off -rw-rw-r--   1 @02858   @ISSTC00       6 Dec  7 18:31 TT

**Comment by ccw-1** [comment]
fixed in source repo.
